# Generated by Django 5.0.9 on 2026-05-11 20:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(help_text='Stock symbol or trading pair (e.g., AAPL, BTC/USD)', max_length=20)),
                ('timeframe', models.CharField(default='1d', help_text='Candlestick timeframe (e.g., 1m, 5m, 1h, 1d)', max_length=10)),
                ('source', models.CharField(default='user_upload', help_text='Data source identifier', max_length=100)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('rows_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_from', models.DateTimeField(blank=True, null=True)),
                ('date_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=dict, help_text='Validation error details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uploaded Dataset',
                'verbose_name_plural': 'Uploaded Datasets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', '-created_at'], name='forecasting_symbol_59baf8_idx'), models.Index(fields=['status'], name='forecasting_status_590e02_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(default='default', help_text='Name of the forecasting model used', max_length=100)),
                ('horizon', models.PositiveIntegerField(help_text='Number of periods to forecast', validators=[django.core.validators.MinValueValidator(1)])),
                ('confidence_level', models.FloatField(default=0.95, help_text='Confidence level (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(1)])),
                ('predictions', models.JSONField(default=list, help_text='Array of predicted values with timestamps')),
                ('statistics', models.JSONField(default=dict, help_text='Prediction statistics (RMSE, MAE, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='forecasting.uploadeddataset')),
            ],
            options={
                'verbose_name': 'Prediction Result',
                'verbose_name_plural': 'Prediction Results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', '-created_at'], name='forecasting_dataset_066a76_idx'), models.Index(fields=['status'], name='forecasting_status_f0f3ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='CandlestickData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('high_low_diff', models.DecimalField(blank=True, decimal_places=8, help_text='High - Low', max_digits=15, null=True)),
                ('close_open_diff', models.DecimalField(blank=True, decimal_places=8, help_text='Close - Open', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candlesticks', to='forecasting.uploadeddataset')),
            ],
            options={
                'verbose_name': 'Candlestick Data',
                'verbose_name_plural': 'Candlestick Data',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['dataset', 'timestamp'], name='forecasting_dataset_3b5ea2_idx'), models.Index(fields=['timestamp'], name='forecasting_timesta_315b3b_idx')],
                'unique_together': {('dataset', 'timestamp')},
            },
        ),
    ]
